// Generated by CoffeeScript 1.6.3
(function() {
  var app, colors, express, handler, http, hub, io, port, server, socket;

  express = require("express");

  colors = require("./app/colors");

  handler = require("./app/eventDenormalizer");

  socket = require("socket.io");

  app = express();

  http = require("http");

  server = http.createServer(app);

  io = socket.listen(server);

  app.configure(function() {
    app.use(express.bodyParser());
    app.use(express["static"](__dirname + "/public"));
    app.set("view engine", "jade");
    return app.set("views", __dirname + "/app/views");
  });

  io.configure(function() {
    return io.set("log level", 1);
  });

  console.log("\nBOOTSTRAPPING:".cyan);

  console.log("1. -> routes".cyan);

  require("./app/routes").actions(app);

  console.log("2. -> message hub".cyan);

  hub = require("./app/hub");

  io.sockets.on("connection", function(socket) {
    var conn;
    conn = socket.handshake.address.address + ":" + socket.handshake.address.port;
    console.log(colors.magenta(conn + " -- connects to socket.io"));
    return socket.on("commands", function(data) {
      console.log(colors.magenta("\n" + conn + " -- sends command " + data.command + ":"));
      console.log(JSON.stringify(data, null, 4));
      return hub.emit(data.command, conn, data);
    });
  });

  hub.on("events", function(data) {
    console.log(colors.cyan("eventDenormalizer -- denormalize event " + data.event));
    handler.handle(data, null, 4);
    console.log(colors.magenta("\nsocket.io -- publish event " + data.event + " to browser"));
    return io.sockets.emit("events", data);
  });

  port = 3000;

  console.log(colors.cyan("\nStarting server on port " + port));

  server.listen(3000);

}).call(this);
