// Generated by CoffeeScript 1.6.3
(function() {
  var Item, colors;

  colors = require("./colors");

  Item = function(id) {
    this.id = id;
    this.text = "";
    this._destroy = false;
    return this.uncommittedEvents = [];
  };

  Item.prototype = {
    createItem: function(evt, callback) {
      evt.payload.id = this.id;
      if (evt.payload.text === "") {
        return callback(new Error("It is not allowed to set an item text to empty string."));
      } else {
        this.apply(evt);
        return callback(null, this.uncommittedEvents);
      }
    },
    changeItem: function(evt, callback) {
      if (evt.payload.text === "") {
        return callback(new Error("It is not allowed to set an item text to empty string."));
      } else {
        this.apply(evt);
        return callback(null, this.uncommittedEvents);
      }
    },
    deleteItem: function(evt, callback) {
      this.apply(evt);
      return callback(null, this.uncommittedEvents);
    },
    apply: function(evt) {
      this["_" + evt.event](evt);
      if (!evt.fromHistory) {
        return this.uncommittedEvents.push(evt);
      }
    },
    _itemCreated: function(evt) {
      return this.text = evt.payload.text;
    },
    _itemChanged: function(evt) {
      return this.text = evt.payload.text;
    },
    _itemDeleted: function(evt) {
      return this._destroy = true;
    },
    loadFromHistory: function(history) {
      var e, i, len, _results;
      i = 0;
      len = history.length;
      _results = [];
      while (i < len) {
        e = history[i].payload;
        e.fromHistory = true;
        this.apply(e);
        _results.push(i++);
      }
      return _results;
    }
  };

  exports.create = function(id) {
    return new Item(id);
  };

}).call(this);
