// Generated by CoffeeScript 1.6.3
(function() {
  var async, colors, eventHandler, store;

  store = require("./storage");

  async = require("async");

  colors = require("./colors");

  eventHandler = {
    handle: function(evt) {
      return eventHandler[evt.event](evt);
    },
    itemCreated: function(evt) {
      return store.save({
        id: evt.payload.id,
        text: evt.payload.text
      }, function(err) {});
    },
    itemChanged: function(evt) {
      return store.load(evt.payload.id, function(err, item) {
        item.text = evt.payload.text;
        return store.save(item, function(err) {});
      });
    },
    itemDeleted: function(evt) {
      return store.del(evt.payload.id, function(err) {});
    }
  };

  exports.handle = eventHandler.handle;

}).call(this);
