// Generated by CoffeeScript 1.6.3
(function() {
  var cmd, colors, evt, map, redis, subscriptions;

  redis = require("redis");

  colors = require("./colors");

  map = require("./msgmap");

  cmd = redis.createClient();

  evt = redis.createClient();

  subscriptions = [];

  exports.emit = function(commandName, sender, message) {
    var data;
    data = map.to(commandName, sender, message);
    console.log(colors.blue("\nhub -- publishing command " + commandName + " to redis:"));
    console.log(data.blue);
    return cmd.publish("commands", data);
  };

  exports.on = function(channel, callback) {
    subscriptions.push({
      channel: channel,
      callback: callback
    });
    return console.log(colors.blue("hub -- subscribers: " + subscriptions.length));
  };

  evt.on("message", function(channel, message) {
    var data;
    data = map.from(channel, message);
    console.log(colors.green("\nhub -- received event " + data.event + " from redis:"));
    console.log(message.green);
    return subscriptions.forEach(function(subscriber) {
      console.log(colors.green("should subscriber " + subscriber + " be notified?"));
      if (channel === subscriber.channel) {
        return subscriber.callback(data);
      }
    });
  });

  evt.subscribe("events");

}).call(this);
