// Generated by CoffeeScript 1.6.3
(function() {
  var map;

  map = {
    to: {
      channelNeedsCustom: function(channel, sender, message) {
        var msg;
        msg = {
          id: message.id,
          command: message.command,
          sender: sender,
          payload: message.payload
        };
        return JSON.stringify(msg, null, 4);
      },
      "default": function(channel, sender, message) {
        var msg;
        msg = {
          id: message.id,
          command: message.command,
          time: new Date(),
          sender: sender,
          payload: message.payload
        };
        return JSON.stringify(msg, null, 4);
      }
    },
    from: {
      channelNeedsCustom: function(channel, message) {
        var data, msg;
        msg = JSON.parse(message);
        data = {
          id: msg.id,
          event: msg.event,
          payload: msg.payload
        };
        return data;
      },
      "default": function(channel, message) {
        var data, msg;
        msg = JSON.parse(message);
        data = {
          id: msg.id,
          event: msg.event,
          payload: msg.payload
        };
        return data;
      }
    }
  };

  exports.to = function(channel, sender, message) {
    if (map.to[channel]) {
      return map.to[channel](channel, sender, message);
    } else {
      return map.to["default"](channel, sender, message);
    }
  };

  exports.from = function(channel, message) {
    if (map.from[channel]) {
      return map.from[channel](channel, message);
    } else {
      return map.from["default"](channel, message);
    }
  };

}).call(this);
